## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: false
dist: trusty
os:
  - linux
julia:
  - 1.4
  - 1.5
  - nightly
notifications:
  email: false

# comment the following lines to disallow failures on nightly julia
matrix:
  allow_failures:
  - julia: nightly

before_script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      brew upgrade cmake
    fi

after_success:
  # push coverage results to Codecov
  - julia -e 'import Pkg;
                     cd(Pkg.dir("BetweenFlags"));
                     Pkg.add("Coverage");
                     using Coverage;
                     Codecov.submit(Codecov.process_folder())'
